### ISSUE TITLE
Synthetic canary analysis for new worker versions

### ISSUE THREAD

**Issue by jlegrone** [DataDog/temporal-worker-controller#16]
Before beginning to send live traffic to new worker versions, enable workers to specify a workflow type that must run once to completion on the new worker version. Eg.

```yaml
apiVersion: temporal.io/v1alpha1
kind: TemporalWorker
# ...
spec:
  cutover:
    strategy: AllAtOnce
    gate:
      workflowType: PreDeployCheck
      timeout: 5m
# ...
```

Deployment gate workflows must:
- Not require input arguments
- Return an error value to indicate success/failure
- Run to completion within the specified timeout

This requires an API change on the temporal server side to enable clients to start workflows on a specific version deterministically before it is added to assignment rules.
